### DB Properties ###
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://ec2-63-33-239-176.eu-west-1.compute.amazonaws.com:5432/d21h8qsucj8hv4"
    username: "htdorixzanadhq"
    ## Commenta se devi collegarti con Xxamp
    password: "dc4bb9e2e0d6436d2f19c9cdfc343e2a04f2e19edf1f27ea3c3421b7f575c715"
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: true
  inizialize: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE
